/**************************************************************************************/
//
// HSM 48X0G GENERATION 6 SOFTWARE
//
//  HARDWARE DEFINITION FILE 
//  Date:       9/15/2008
//  Tools:      RVCT Build 674
//  Target:     Freescale iMX25
//
//======================================================================================
// Revision information
//======================================================================================
// $RCSfile: db_shared/Hardware_Header_Files/iMX25/iMX25_IOMUX.h $
// $Revision: 1.6 $
// $Date: 2011/06/28 13:26:52EDT $
//======================================================================================

//======================================================================================
//------------------------------------------------------------------------------
// Header:  iMX25_IOMUX.h
//
// Provides definitions for External Signals and Pin Multiplexing
// Refer to Chapter 4 of the iMX25 Reference Manual
//
//------------------------------------------------------------------------------
#ifndef IMX25_IOMUX_H_
#define IMX25_IOMUX_H_
#include "Hardware_Width_Defines.h"		//Used for the Mask Width
//------------------------------------------------------------------------------
// Registers
//------------------------------------------------------------------------------
// #########################################
// # IOMUXC                                #
// #########################################
#define IOMUXC_BASE_ADDR           							0x43FAC000U

#define IOMUXC_GPR1     									(IOMUXC_BASE_ADDR+0x0U)
#define IOMUXC_OBSERVE_INT_MUX     							(IOMUXC_BASE_ADDR+0x4U)

#define IOMUXC_SW_MUX_CTL_PAD_A10     						(IOMUXC_BASE_ADDR+0x8U)
#define IOMUXC_SW_MUX_CTL_PAD_A13     						(IOMUXC_BASE_ADDR+0xcU)
#define IOMUXC_SW_MUX_CTL_PAD_A14     						(IOMUXC_BASE_ADDR+0x10U)
#define IOMUXC_SW_MUX_CTL_PAD_A15     						(IOMUXC_BASE_ADDR+0x14U)
#define IOMUXC_SW_MUX_CTL_PAD_A16     						(IOMUXC_BASE_ADDR+0x18U)
#define IOMUXC_SW_MUX_CTL_PAD_A17     						(IOMUXC_BASE_ADDR+0x1cU)
#define IOMUXC_SW_MUX_CTL_PAD_A18     						(IOMUXC_BASE_ADDR+0x20U)
#define IOMUXC_SW_MUX_CTL_PAD_A19     						(IOMUXC_BASE_ADDR+0x24U)
#define IOMUXC_SW_MUX_CTL_PAD_A20     						(IOMUXC_BASE_ADDR+0x28U)
#define IOMUXC_SW_MUX_CTL_PAD_A21     						(IOMUXC_BASE_ADDR+0x2cU)
#define IOMUXC_SW_MUX_CTL_PAD_A22     						(IOMUXC_BASE_ADDR+0x30U)
#define IOMUXC_SW_MUX_CTL_PAD_A23     						(IOMUXC_BASE_ADDR+0x34U)
#define IOMUXC_SW_MUX_CTL_PAD_A24     						(IOMUXC_BASE_ADDR+0x38U)
#define IOMUXC_SW_MUX_CTL_PAD_A25     						(IOMUXC_BASE_ADDR+0x3cU)
#define IOMUXC_SW_MUX_CTL_PAD_EB0     						(IOMUXC_BASE_ADDR+0x40U)
#define IOMUXC_SW_MUX_CTL_PAD_EB1     						(IOMUXC_BASE_ADDR+0x44U)
#define IOMUXC_SW_MUX_CTL_PAD_OE     						(IOMUXC_BASE_ADDR+0x48U)
#define IOMUXC_SW_MUX_CTL_PAD_CS0     						(IOMUXC_BASE_ADDR+0x4cU)
#define IOMUXC_SW_MUX_CTL_PAD_CS1     						(IOMUXC_BASE_ADDR+0x50U)
#define IOMUXC_SW_MUX_CTL_PAD_CS4     						(IOMUXC_BASE_ADDR+0x54U)
#define IOMUXC_SW_MUX_CTL_PAD_CS5     						(IOMUXC_BASE_ADDR+0x58U)
#define IOMUXC_SW_MUX_CTL_PAD_NF_CE0     					(IOMUXC_BASE_ADDR+0x5cU)
#define IOMUXC_SW_MUX_CTL_PAD_ECB     						(IOMUXC_BASE_ADDR+0x60U)
#define IOMUXC_SW_MUX_CTL_PAD_LBA     						(IOMUXC_BASE_ADDR+0x64U)
#define IOMUXC_SW_MUX_CTL_PAD_BCLK     						(IOMUXC_BASE_ADDR+0x68U)
#define IOMUXC_SW_MUX_CTL_PAD_RW     						(IOMUXC_BASE_ADDR+0x6cU)
#define IOMUXC_SW_MUX_CTL_PAD_NFWE_B     					(IOMUXC_BASE_ADDR+0x70U)
#define IOMUXC_SW_MUX_CTL_PAD_NFRE_B     					(IOMUXC_BASE_ADDR+0x74U)
#define IOMUXC_SW_MUX_CTL_PAD_NFALE     					(IOMUXC_BASE_ADDR+0x78U)
#define IOMUXC_SW_MUX_CTL_PAD_NFCLE     					(IOMUXC_BASE_ADDR+0x7cU)
#define IOMUXC_SW_MUX_CTL_PAD_NFWP_B     					(IOMUXC_BASE_ADDR+0x80U)
#define IOMUXC_SW_MUX_CTL_PAD_NFRB     						(IOMUXC_BASE_ADDR+0x84U)
#define IOMUXC_SW_MUX_CTL_PAD_D15     						(IOMUXC_BASE_ADDR+0x88U)
#define IOMUXC_SW_MUX_CTL_PAD_D14     						(IOMUXC_BASE_ADDR+0x8cU)
#define IOMUXC_SW_MUX_CTL_PAD_D13     						(IOMUXC_BASE_ADDR+0x90U)
#define IOMUXC_SW_MUX_CTL_PAD_D12     						(IOMUXC_BASE_ADDR+0x94U)
#define IOMUXC_SW_MUX_CTL_PAD_D11     						(IOMUXC_BASE_ADDR+0x98U)
#define IOMUXC_SW_MUX_CTL_PAD_D10     						(IOMUXC_BASE_ADDR+0x9cU)
#define IOMUXC_SW_MUX_CTL_PAD_D9     						(IOMUXC_BASE_ADDR+0xa0U)
#define IOMUXC_SW_MUX_CTL_PAD_D8     						(IOMUXC_BASE_ADDR+0xa4U)
#define IOMUXC_SW_MUX_CTL_PAD_D7     						(IOMUXC_BASE_ADDR+0xa8U)
#define IOMUXC_SW_MUX_CTL_PAD_D6     						(IOMUXC_BASE_ADDR+0xacU)
#define IOMUXC_SW_MUX_CTL_PAD_D5     						(IOMUXC_BASE_ADDR+0xb0U)
#define IOMUXC_SW_MUX_CTL_PAD_D4     						(IOMUXC_BASE_ADDR+0xb4U)
#define IOMUXC_SW_MUX_CTL_PAD_D3     						(IOMUXC_BASE_ADDR+0xb8U)
#define IOMUXC_SW_MUX_CTL_PAD_D2     						(IOMUXC_BASE_ADDR+0xbcU)
#define IOMUXC_SW_MUX_CTL_PAD_D1     						(IOMUXC_BASE_ADDR+0xc0U)
#define IOMUXC_SW_MUX_CTL_PAD_D0     						(IOMUXC_BASE_ADDR+0xc4U)
#define IOMUXC_SW_MUX_CTL_PAD_LD0     						(IOMUXC_BASE_ADDR+0xc8U)
#define IOMUXC_SW_MUX_CTL_PAD_LD1     						(IOMUXC_BASE_ADDR+0xccU)
#define IOMUXC_SW_MUX_CTL_PAD_LD2     						(IOMUXC_BASE_ADDR+0xd0U)
#define IOMUXC_SW_MUX_CTL_PAD_LD3     						(IOMUXC_BASE_ADDR+0xd4U)
#define IOMUXC_SW_MUX_CTL_PAD_LD4     						(IOMUXC_BASE_ADDR+0xd8U)
#define IOMUXC_SW_MUX_CTL_PAD_LD5     						(IOMUXC_BASE_ADDR+0xdcU)
#define IOMUXC_SW_MUX_CTL_PAD_LD6     						(IOMUXC_BASE_ADDR+0xe0U)
#define IOMUXC_SW_MUX_CTL_PAD_LD7     						(IOMUXC_BASE_ADDR+0xe4U)
#define IOMUXC_SW_MUX_CTL_PAD_LD8     						(IOMUXC_BASE_ADDR+0xe8U)
#define IOMUXC_SW_MUX_CTL_PAD_LD9     						(IOMUXC_BASE_ADDR+0xecU)
#define IOMUXC_SW_MUX_CTL_PAD_LD10     						(IOMUXC_BASE_ADDR+0xf0U)
#define IOMUXC_SW_MUX_CTL_PAD_LD11     						(IOMUXC_BASE_ADDR+0xf4U)
#define IOMUXC_SW_MUX_CTL_PAD_LD12     						(IOMUXC_BASE_ADDR+0xf8U)
#define IOMUXC_SW_MUX_CTL_PAD_LD13     						(IOMUXC_BASE_ADDR+0xfcU)
#define IOMUXC_SW_MUX_CTL_PAD_LD14     						(IOMUXC_BASE_ADDR+0x100U)
#define IOMUXC_SW_MUX_CTL_PAD_LD15     						(IOMUXC_BASE_ADDR+0x104U)
#define IOMUXC_SW_MUX_CTL_PAD_HSYNC     					(IOMUXC_BASE_ADDR+0x108U)
#define IOMUXC_SW_MUX_CTL_PAD_VSYNC     					(IOMUXC_BASE_ADDR+0x10cU)
#define IOMUXC_SW_MUX_CTL_PAD_LSCLK     					(IOMUXC_BASE_ADDR+0x110U)
#define IOMUXC_SW_MUX_CTL_PAD_OE_ACD     					(IOMUXC_BASE_ADDR+0x114U)
#define IOMUXC_SW_MUX_CTL_PAD_CONTRAST     					(IOMUXC_BASE_ADDR+0x118U)
#define IOMUXC_SW_MUX_CTL_PAD_PWM     						(IOMUXC_BASE_ADDR+0x11cU)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D2     					(IOMUXC_BASE_ADDR+0x120U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D3     					(IOMUXC_BASE_ADDR+0x124U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D4     					(IOMUXC_BASE_ADDR+0x128U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D5     					(IOMUXC_BASE_ADDR+0x12cU)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D6     					(IOMUXC_BASE_ADDR+0x130U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D7     					(IOMUXC_BASE_ADDR+0x134U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D8     					(IOMUXC_BASE_ADDR+0x138U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_D9     					(IOMUXC_BASE_ADDR+0x13cU)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_MCLK     					(IOMUXC_BASE_ADDR+0x140U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_VSYNC     				(IOMUXC_BASE_ADDR+0x144U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_HSYNC     				(IOMUXC_BASE_ADDR+0x148U)
#define IOMUXC_SW_MUX_CTL_PAD_CSI_PIXCLK     				(IOMUXC_BASE_ADDR+0x14cU)
#define IOMUXC_SW_MUX_CTL_PAD_I2C1_CLK     					(IOMUXC_BASE_ADDR+0x150U)
#define IOMUXC_SW_MUX_CTL_PAD_I2C1_DAT     					(IOMUXC_BASE_ADDR+0x154U)
#define IOMUXC_SW_MUX_CTL_PAD_CSPI1_MOSI     				(IOMUXC_BASE_ADDR+0x158U)
#define IOMUXC_SW_MUX_CTL_PAD_CSPI1_MISO     				(IOMUXC_BASE_ADDR+0x15cU)
#define IOMUXC_SW_MUX_CTL_PAD_CSPI1_SS0     				(IOMUXC_BASE_ADDR+0x160U)
#define IOMUXC_SW_MUX_CTL_PAD_CSPI1_SS1     				(IOMUXC_BASE_ADDR+0x164U)
#define IOMUXC_SW_MUX_CTL_PAD_CSPI1_SCLK     				(IOMUXC_BASE_ADDR+0x168U)
#define IOMUXC_SW_MUX_CTL_PAD_CSPI1_RDY     				(IOMUXC_BASE_ADDR+0x16cU)
#define IOMUXC_SW_MUX_CTL_PAD_UART1_RXD     				(IOMUXC_BASE_ADDR+0x170U)
#define IOMUXC_SW_MUX_CTL_PAD_UART1_TXD     				(IOMUXC_BASE_ADDR+0x174U)
#define IOMUXC_SW_MUX_CTL_PAD_UART1_RTS     				(IOMUXC_BASE_ADDR+0x178U)
#define IOMUXC_SW_MUX_CTL_PAD_UART1_CTS     				(IOMUXC_BASE_ADDR+0x17cU)
#define IOMUXC_SW_MUX_CTL_PAD_UART2_RXD     				(IOMUXC_BASE_ADDR+0x180U)
#define IOMUXC_SW_MUX_CTL_PAD_UART2_TXD     				(IOMUXC_BASE_ADDR+0x184U)
#define IOMUXC_SW_MUX_CTL_PAD_UART2_RTS     				(IOMUXC_BASE_ADDR+0x188U)
#define IOMUXC_SW_MUX_CTL_PAD_UART2_CTS     				(IOMUXC_BASE_ADDR+0x18cU)
#define IOMUXC_SW_MUX_CTL_PAD_SD1_CMD     					(IOMUXC_BASE_ADDR+0x190U)
#define IOMUXC_SW_MUX_CTL_PAD_SD1_CLK     					(IOMUXC_BASE_ADDR+0x194U)
#define IOMUXC_SW_MUX_CTL_PAD_SD1_DATA0     				(IOMUXC_BASE_ADDR+0x198U)
#define IOMUXC_SW_MUX_CTL_PAD_SD1_DATA1     				(IOMUXC_BASE_ADDR+0x19cU)
#define IOMUXC_SW_MUX_CTL_PAD_SD1_DATA2     				(IOMUXC_BASE_ADDR+0x1a0U)
#define IOMUXC_SW_MUX_CTL_PAD_SD1_DATA3     				(IOMUXC_BASE_ADDR+0x1a4U)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_ROW0     					(IOMUXC_BASE_ADDR+0x1a8U)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_ROW1     					(IOMUXC_BASE_ADDR+0x1acU)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_ROW2     					(IOMUXC_BASE_ADDR+0x1b0U)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_ROW3     					(IOMUXC_BASE_ADDR+0x1b4U)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_COL0     					(IOMUXC_BASE_ADDR+0x1b8U)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_COL1     					(IOMUXC_BASE_ADDR+0x1bcU)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_COL2     					(IOMUXC_BASE_ADDR+0x1c0U)
#define IOMUXC_SW_MUX_CTL_PAD_KPP_COL3     					(IOMUXC_BASE_ADDR+0x1c4U)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_MDC     					(IOMUXC_BASE_ADDR+0x1c8U)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_MDIO     					(IOMUXC_BASE_ADDR+0x1ccU)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_TDATA0     				(IOMUXC_BASE_ADDR+0x1d0U)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_TDATA1     				(IOMUXC_BASE_ADDR+0x1d4U)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_TX_EN     				(IOMUXC_BASE_ADDR+0x1d8U)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_RDATA0     				(IOMUXC_BASE_ADDR+0x1dcU)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_RDATA1     				(IOMUXC_BASE_ADDR+0x1e0U)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_RX_DV     				(IOMUXC_BASE_ADDR+0x1e4U)
#define IOMUXC_SW_MUX_CTL_PAD_FEC_TX_CLK     				(IOMUXC_BASE_ADDR+0x1e8U)
#define IOMUXC_SW_MUX_CTL_PAD_RTCK     						(IOMUXC_BASE_ADDR+0x1ecU)
#define IOMUXC_SW_MUX_CTL_PAD_DE_B     						(IOMUXC_BASE_ADDR+0x1f0U)
#define IOMUXC_SW_MUX_CTL_PAD_GPIO_A     					(IOMUXC_BASE_ADDR+0x1f4U)
#define IOMUXC_SW_MUX_CTL_PAD_GPIO_B     					(IOMUXC_BASE_ADDR+0x1f8U)
#define IOMUXC_SW_MUX_CTL_PAD_GPIO_C     					(IOMUXC_BASE_ADDR+0x1fcU)
#define IOMUXC_SW_MUX_CTL_PAD_GPIO_D     					(IOMUXC_BASE_ADDR+0x200U)
#define IOMUXC_SW_MUX_CTL_PAD_GPIO_E     					(IOMUXC_BASE_ADDR+0x204U)
#define IOMUXC_SW_MUX_CTL_PAD_GPIO_F     					(IOMUXC_BASE_ADDR+0x208U)
#define IOMUXC_SW_MUX_CTL_PAD_EXT_ARMCLK     				(IOMUXC_BASE_ADDR+0x20cU)
#define IOMUXC_SW_MUX_CTL_PAD_UPLL_BYPCLK     				(IOMUXC_BASE_ADDR+0x210U)
#define IOMUXC_SW_MUX_CTL_PAD_VSTBY_REQ     				(IOMUXC_BASE_ADDR+0x214U)
#define IOMUXC_SW_MUX_CTL_PAD_VSTBY_ACK     				(IOMUXC_BASE_ADDR+0x218U)
#define IOMUXC_SW_MUX_CTL_PAD_POWER_FAIL     				(IOMUXC_BASE_ADDR+0x21cU)
#define IOMUXC_SW_MUX_CTL_PAD_CLKO     						(IOMUXC_BASE_ADDR+0x220U)
#define IOMUXC_SW_MUX_CTL_PAD_BOOT_MODE0     				(IOMUXC_BASE_ADDR+0x224U)
#define IOMUXC_SW_MUX_CTL_PAD_BOOT_MODE1     				(IOMUXC_BASE_ADDR+0x228U)

#define IOMUXC_SW_PAD_CTL_PAD_A13     						(IOMUXC_BASE_ADDR+0x22cU)
#define IOMUXC_SW_PAD_CTL_PAD_A14     						(IOMUXC_BASE_ADDR+0x230U)
#define IOMUXC_SW_PAD_CTL_PAD_A15     						(IOMUXC_BASE_ADDR+0x234U)
#define IOMUXC_SW_PAD_CTL_PAD_A17     						(IOMUXC_BASE_ADDR+0x238U)
#define IOMUXC_SW_PAD_CTL_PAD_A18     						(IOMUXC_BASE_ADDR+0x23cU)
#define IOMUXC_SW_PAD_CTL_PAD_A19     						(IOMUXC_BASE_ADDR+0x240U)
#define IOMUXC_SW_PAD_CTL_PAD_A20     						(IOMUXC_BASE_ADDR+0x244U)
#define IOMUXC_SW_PAD_CTL_PAD_A21     						(IOMUXC_BASE_ADDR+0x248U)
#define IOMUXC_SW_PAD_CTL_PAD_A23     						(IOMUXC_BASE_ADDR+0x24cU)
#define IOMUXC_SW_PAD_CTL_PAD_A24     						(IOMUXC_BASE_ADDR+0x250U)
#define IOMUXC_SW_PAD_CTL_PAD_A25     						(IOMUXC_BASE_ADDR+0x254U)
#define IOMUXC_SW_PAD_CTL_PAD_EB0     						(IOMUXC_BASE_ADDR+0x258U)
#define IOMUXC_SW_PAD_CTL_PAD_EB1     						(IOMUXC_BASE_ADDR+0x25cU)
#define IOMUXC_SW_PAD_CTL_PAD_OE     						(IOMUXC_BASE_ADDR+0x260U)
#define IOMUXC_SW_PAD_CTL_PAD_CS4     						(IOMUXC_BASE_ADDR+0x264U)
#define IOMUXC_SW_PAD_CTL_PAD_CS5     						(IOMUXC_BASE_ADDR+0x268U)
#define IOMUXC_SW_PAD_CTL_PAD_NF_CE0     					(IOMUXC_BASE_ADDR+0x26cU)
#define IOMUXC_SW_PAD_CTL_PAD_ECB     						(IOMUXC_BASE_ADDR+0x270U)
#define IOMUXC_SW_PAD_CTL_PAD_LBA     						(IOMUXC_BASE_ADDR+0x274U)
#define IOMUXC_SW_PAD_CTL_PAD_RW     						(IOMUXC_BASE_ADDR+0x278U)
#define IOMUXC_SW_PAD_CTL_PAD_NFRB     						(IOMUXC_BASE_ADDR+0x27cU)
#define IOMUXC_SW_PAD_CTL_PAD_D15     						(IOMUXC_BASE_ADDR+0x280U)
#define IOMUXC_SW_PAD_CTL_PAD_D14     						(IOMUXC_BASE_ADDR+0x284U)
#define IOMUXC_SW_PAD_CTL_PAD_D13     						(IOMUXC_BASE_ADDR+0x288U)
#define IOMUXC_SW_PAD_CTL_PAD_D12     						(IOMUXC_BASE_ADDR+0x28cU)
#define IOMUXC_SW_PAD_CTL_PAD_D11     						(IOMUXC_BASE_ADDR+0x290U)
#define IOMUXC_SW_PAD_CTL_PAD_D10     						(IOMUXC_BASE_ADDR+0x294U)
#define IOMUXC_SW_PAD_CTL_PAD_D9     						(IOMUXC_BASE_ADDR+0x298U)
#define IOMUXC_SW_PAD_CTL_PAD_D8     						(IOMUXC_BASE_ADDR+0x29cU)
#define IOMUXC_SW_PAD_CTL_PAD_D7     						(IOMUXC_BASE_ADDR+0x2a0U)
#define IOMUXC_SW_PAD_CTL_PAD_D6     						(IOMUXC_BASE_ADDR+0x2a4U)
#define IOMUXC_SW_PAD_CTL_PAD_D5     						(IOMUXC_BASE_ADDR+0x2a8U)
#define IOMUXC_SW_PAD_CTL_PAD_D4     						(IOMUXC_BASE_ADDR+0x2acU)
#define IOMUXC_SW_PAD_CTL_PAD_D3     						(IOMUXC_BASE_ADDR+0x2b0U)
#define IOMUXC_SW_PAD_CTL_PAD_D2     						(IOMUXC_BASE_ADDR+0x2b4U)
#define IOMUXC_SW_PAD_CTL_PAD_D1     						(IOMUXC_BASE_ADDR+0x2b8U)
#define IOMUXC_SW_PAD_CTL_PAD_D0     						(IOMUXC_BASE_ADDR+0x2bcU)
#define IOMUXC_SW_PAD_CTL_PAD_LD0     						(IOMUXC_BASE_ADDR+0x2c0U)
#define IOMUXC_SW_PAD_CTL_PAD_LD1     						(IOMUXC_BASE_ADDR+0x2c4U)
#define IOMUXC_SW_PAD_CTL_PAD_LD2     						(IOMUXC_BASE_ADDR+0x2c8U)
#define IOMUXC_SW_PAD_CTL_PAD_LD3     						(IOMUXC_BASE_ADDR+0x2ccU)
#define IOMUXC_SW_PAD_CTL_PAD_LD4     						(IOMUXC_BASE_ADDR+0x2d0U)
#define IOMUXC_SW_PAD_CTL_PAD_LD5     						(IOMUXC_BASE_ADDR+0x2d4U)
#define IOMUXC_SW_PAD_CTL_PAD_LD6     						(IOMUXC_BASE_ADDR+0x2d8U)
#define IOMUXC_SW_PAD_CTL_PAD_LD7     						(IOMUXC_BASE_ADDR+0x2dcU)
#define IOMUXC_SW_PAD_CTL_PAD_LD8     						(IOMUXC_BASE_ADDR+0x2e0U)
#define IOMUXC_SW_PAD_CTL_PAD_LD9     						(IOMUXC_BASE_ADDR+0x2e4U)
#define IOMUXC_SW_PAD_CTL_PAD_LD10     						(IOMUXC_BASE_ADDR+0x2e8U)
#define IOMUXC_SW_PAD_CTL_PAD_LD11     						(IOMUXC_BASE_ADDR+0x2ecU)
#define IOMUXC_SW_PAD_CTL_PAD_LD12     						(IOMUXC_BASE_ADDR+0x2f0U)
#define IOMUXC_SW_PAD_CTL_PAD_LD13     						(IOMUXC_BASE_ADDR+0x2f4U)
#define IOMUXC_SW_PAD_CTL_PAD_LD14     						(IOMUXC_BASE_ADDR+0x2f8U)
#define IOMUXC_SW_PAD_CTL_PAD_LD15     						(IOMUXC_BASE_ADDR+0x2fcU)
#define IOMUXC_SW_PAD_CTL_PAD_HSYNC     					(IOMUXC_BASE_ADDR+0x300U)
#define IOMUXC_SW_PAD_CTL_PAD_VSYNC     					(IOMUXC_BASE_ADDR+0x304U)
#define IOMUXC_SW_PAD_CTL_PAD_LSCLK     					(IOMUXC_BASE_ADDR+0x308U)
#define IOMUXC_SW_PAD_CTL_PAD_OE_ACD     					(IOMUXC_BASE_ADDR+0x30cU)
#define IOMUXC_SW_PAD_CTL_PAD_CONTRAST     					(IOMUXC_BASE_ADDR+0x310U)
#define IOMUXC_SW_PAD_CTL_PAD_PWM     						(IOMUXC_BASE_ADDR+0x314U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D2     					(IOMUXC_BASE_ADDR+0x318U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D3     					(IOMUXC_BASE_ADDR+0x31cU)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D4     					(IOMUXC_BASE_ADDR+0x320U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D5     					(IOMUXC_BASE_ADDR+0x324U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D6     					(IOMUXC_BASE_ADDR+0x328U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D7     					(IOMUXC_BASE_ADDR+0x32cU)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D8     					(IOMUXC_BASE_ADDR+0x330U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_D9     					(IOMUXC_BASE_ADDR+0x334U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_MCLK     					(IOMUXC_BASE_ADDR+0x338U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_VSYNC     				(IOMUXC_BASE_ADDR+0x33cU)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_HSYNC     				(IOMUXC_BASE_ADDR+0x340U)
#define IOMUXC_SW_PAD_CTL_PAD_CSI_PIXCLK     				(IOMUXC_BASE_ADDR+0x344U)
#define IOMUXC_SW_PAD_CTL_PAD_I2C1_CLK     					(IOMUXC_BASE_ADDR+0x348U)
#define IOMUXC_SW_PAD_CTL_PAD_I2C1_DAT     					(IOMUXC_BASE_ADDR+0x34cU)
#define IOMUXC_SW_PAD_CTL_PAD_CSPI1_MOSI     				(IOMUXC_BASE_ADDR+0x350U)
#define IOMUXC_SW_PAD_CTL_PAD_CSPI1_MISO     				(IOMUXC_BASE_ADDR+0x354U)
#define IOMUXC_SW_PAD_CTL_PAD_CSPI1_SS0     				(IOMUXC_BASE_ADDR+0x358U)
#define IOMUXC_SW_PAD_CTL_PAD_CSPI1_SS1     				(IOMUXC_BASE_ADDR+0x35cU)
#define IOMUXC_SW_PAD_CTL_PAD_CSPI1_SCLK     				(IOMUXC_BASE_ADDR+0x360U)
#define IOMUXC_SW_PAD_CTL_PAD_CSPI1_RDY     				(IOMUXC_BASE_ADDR+0x364U)
#define IOMUXC_SW_PAD_CTL_PAD_UART1_RXD     				(IOMUXC_BASE_ADDR+0x368U)
#define IOMUXC_SW_PAD_CTL_PAD_UART1_TXD     				(IOMUXC_BASE_ADDR+0x36cU)
#define IOMUXC_SW_PAD_CTL_PAD_UART1_RTS     				(IOMUXC_BASE_ADDR+0x370U)
#define IOMUXC_SW_PAD_CTL_PAD_UART1_CTS     				(IOMUXC_BASE_ADDR+0x374U)
#define IOMUXC_SW_PAD_CTL_PAD_UART2_RXD     				(IOMUXC_BASE_ADDR+0x378U)
#define IOMUXC_SW_PAD_CTL_PAD_UART2_TXD     				(IOMUXC_BASE_ADDR+0x37cU)
#define IOMUXC_SW_PAD_CTL_PAD_UART2_RTS     				(IOMUXC_BASE_ADDR+0x380U)
#define IOMUXC_SW_PAD_CTL_PAD_UART2_CTS     				(IOMUXC_BASE_ADDR+0x384U)
#define IOMUXC_SW_PAD_CTL_PAD_SD1_CMD     					(IOMUXC_BASE_ADDR+0x388U)
#define IOMUXC_SW_PAD_CTL_PAD_SD1_CLK     					(IOMUXC_BASE_ADDR+0x38cU)
#define IOMUXC_SW_PAD_CTL_PAD_SD1_DATA0     				(IOMUXC_BASE_ADDR+0x390U)
#define IOMUXC_SW_PAD_CTL_PAD_SD1_DATA1     				(IOMUXC_BASE_ADDR+0x394U)
#define IOMUXC_SW_PAD_CTL_PAD_SD1_DATA2     				(IOMUXC_BASE_ADDR+0x398U)
#define IOMUXC_SW_PAD_CTL_PAD_SD1_DATA3     				(IOMUXC_BASE_ADDR+0x39cU)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_ROW0     					(IOMUXC_BASE_ADDR+0x3a0U)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_ROW1     					(IOMUXC_BASE_ADDR+0x3a4U)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_ROW2     					(IOMUXC_BASE_ADDR+0x3a8U)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_ROW3     					(IOMUXC_BASE_ADDR+0x3acU)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_COL0     					(IOMUXC_BASE_ADDR+0x3b0U)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_COL1     					(IOMUXC_BASE_ADDR+0x3b4U)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_COL2     					(IOMUXC_BASE_ADDR+0x3b8U)
#define IOMUXC_SW_PAD_CTL_PAD_KPP_COL3     					(IOMUXC_BASE_ADDR+0x3bcU)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_MDC     					(IOMUXC_BASE_ADDR+0x3c0U)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_MDIO     					(IOMUXC_BASE_ADDR+0x3c4U)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_TDATA0     				(IOMUXC_BASE_ADDR+0x3c8U)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_TDATA1     				(IOMUXC_BASE_ADDR+0x3ccU)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_TX_EN     				(IOMUXC_BASE_ADDR+0x3d0U)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_RDATA0     				(IOMUXC_BASE_ADDR+0x3d4U)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_RDATA1     				(IOMUXC_BASE_ADDR+0x3d8U)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_RX_DV     				(IOMUXC_BASE_ADDR+0x3dcU)
#define IOMUXC_SW_PAD_CTL_PAD_FEC_TX_CLK     				(IOMUXC_BASE_ADDR+0x3e0U)
#define IOMUXC_SW_PAD_CTL_PAD_RTCK     						(IOMUXC_BASE_ADDR+0x3e4U)
#define IOMUXC_SW_PAD_CTL_PAD_TDO     						(IOMUXC_BASE_ADDR+0x3e8U)
#define IOMUXC_SW_PAD_CTL_PAD_DE_B     						(IOMUXC_BASE_ADDR+0x3ecU)
#define IOMUXC_SW_PAD_CTL_PAD_GPIO_A     					(IOMUXC_BASE_ADDR+0x3f0U)
#define IOMUXC_SW_PAD_CTL_PAD_GPIO_B     					(IOMUXC_BASE_ADDR+0x3f4U)
#define IOMUXC_SW_PAD_CTL_PAD_GPIO_C     					(IOMUXC_BASE_ADDR+0x3f8U)
#define IOMUXC_SW_PAD_CTL_PAD_GPIO_D     					(IOMUXC_BASE_ADDR+0x3fcU)
#define IOMUXC_SW_PAD_CTL_PAD_GPIO_E     					(IOMUXC_BASE_ADDR+0x400U)
#define IOMUXC_SW_PAD_CTL_PAD_GPIO_F     					(IOMUXC_BASE_ADDR+0x404U)
#define IOMUXC_SW_PAD_CTL_PAD_VSTBY_REQ     				(IOMUXC_BASE_ADDR+0x408U)
#define IOMUXC_SW_PAD_CTL_PAD_VSTBY_ACK     				(IOMUXC_BASE_ADDR+0x40cU)
#define IOMUXC_SW_PAD_CTL_PAD_POWER_FAIL     				(IOMUXC_BASE_ADDR+0x410U)
#define IOMUXC_SW_PAD_CTL_PAD_CLKO     						(IOMUXC_BASE_ADDR+0x414U)

#define IOMUXC_SW_PAD_CTL_GRP_DVS_MISC     					(IOMUXC_BASE_ADDR+0x418U)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_FEC     					(IOMUXC_BASE_ADDR+0x41cU)
#define IOMUXC_SW_PAD_CTL_GRP_DVS_JTAG     					(IOMUXC_BASE_ADDR+0x420U)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_NFC     					(IOMUXC_BASE_ADDR+0x424U)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_CSI     					(IOMUXC_BASE_ADDR+0x428U)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_WEIM     					(IOMUXC_BASE_ADDR+0x42cU)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_DDR     					(IOMUXC_BASE_ADDR+0x430U)
#define IOMUXC_SW_PAD_CTL_GRP_DVS_CRM     					(IOMUXC_BASE_ADDR+0x434U)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_KPP     					(IOMUXC_BASE_ADDR+0x438U)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_SDHC1     				(IOMUXC_BASE_ADDR+0x43cU)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_LCD     					(IOMUXC_BASE_ADDR+0x440U)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_UART     					(IOMUXC_BASE_ADDR+0x444U)
#define IOMUXC_SW_PAD_CTL_GRP_DVS_NFC     					(IOMUXC_BASE_ADDR+0x448U)
#define IOMUXC_SW_PAD_CTL_GRP_DVS_CSI     					(IOMUXC_BASE_ADDR+0x44cU)
#define IOMUXC_SW_PAD_CTL_GRP_DSE_CSPI1     				(IOMUXC_BASE_ADDR+0x450U)
#define IOMUXC_SW_PAD_CTL_GRP_DDRTYPE     					(IOMUXC_BASE_ADDR+0x454U)
#define IOMUXC_SW_PAD_CTL_GRP_DVS_SDHC1     				(IOMUXC_BASE_ADDR+0x458U)
#define IOMUXC_SW_PAD_CTL_GRP_DVS_LCD     					(IOMUXC_BASE_ADDR+0x45cU)

#define IOMUXC_AUDMUX_P4_INPUT_DA_AMX_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x460U)
#define IOMUXC_AUDMUX_P4_INPUT_DB_AMX_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x464U)
#define IOMUXC_AUDMUX_P4_INPUT_RXCLK_AMX_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x468U)
#define IOMUXC_AUDMUX_P4_INPUT_RXFS_AMX_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x46cU)
#define IOMUXC_AUDMUX_P4_INPUT_TXCLK_AMX_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x470U)
#define IOMUXC_AUDMUX_P4_INPUT_TXFS_AMX_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x474U)
#define IOMUXC_AUDMUX_P7_INPUT_DA_AMX_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x478U)
#define IOMUXC_AUDMUX_P7_INPUT_TXFS_AMX_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x47cU)

#define IOMUXC_CAN1_IPP_IND_CANRX_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x480U)
#define IOMUXC_CAN2_IPP_IND_CANRX_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x484U)

#define IOMUXC_CSI_IPP_CSI_D_0_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x488U)
#define IOMUXC_CSI_IPP_CSI_D_1_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x48cU)

#define IOMUXC_CSPI1_IPP_IND_SS3_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x490U)
#define IOMUXC_CSPI2_IPP_CSPI_CLK_IN_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x494U)
#define IOMUXC_CSPI2_IPP_IND_DATAREADY_B_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x498U)
#define IOMUXC_CSPI2_IPP_IND_MISO_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x49cU)
#define IOMUXC_CSPI2_IPP_IND_MOSI_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4a0U)
#define IOMUXC_CSPI2_IPP_IND_SS0_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4a4U)
#define IOMUXC_CSPI2_IPP_IND_SS1_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4a8U)
#define IOMUXC_CSPI3_IPP_CSPI_CLK_IN_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4acU)
#define IOMUXC_CSPI3_IPP_IND_DATAREADY_B_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x4b0U)
#define IOMUXC_CSPI3_IPP_IND_MISO_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4b4U)
#define IOMUXC_CSPI3_IPP_IND_MOSI_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4b8U)
#define IOMUXC_CSPI3_IPP_IND_SS0_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4bcU)
#define IOMUXC_CSPI3_IPP_IND_SS1_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4c0U)
#define IOMUXC_CSPI3_IPP_IND_SS2_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4c4U)
#define IOMUXC_CSPI3_IPP_IND_SS3_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4c8U)

#define IOMUXC_ESDHC1_IPP_DAT4_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4ccU)
#define IOMUXC_ESDHC1_IPP_DAT5_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4d0U)
#define IOMUXC_ESDHC1_IPP_DAT6_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4d4U)
#define IOMUXC_ESDHC1_IPP_DAT7_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4d8U)
#define IOMUXC_ESDHC2_IPP_CARD_CLK_IN_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x4dcU)
#define IOMUXC_ESDHC2_IPP_CMD_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4e0U)
#define IOMUXC_ESDHC2_IPP_DAT0_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4e4U)
#define IOMUXC_ESDHC2_IPP_DAT1_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4e8U)
#define IOMUXC_ESDHC2_IPP_DAT2_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4ecU)
#define IOMUXC_ESDHC2_IPP_DAT3_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4f0U)
#define IOMUXC_ESDHC2_IPP_DAT4_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4f4U)
#define IOMUXC_ESDHC2_IPP_DAT5_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4f8U)
#define IOMUXC_ESDHC2_IPP_DAT6_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x4fcU)
#define IOMUXC_ESDHC2_IPP_DAT7_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x500U)

#define IOMUXC_FEC_FEC_COL_SELECT_INPUT     				(IOMUXC_BASE_ADDR+0x504U)
#define IOMUXC_FEC_FEC_CRS_SELECT_INPUT     				(IOMUXC_BASE_ADDR+0x508U)
#define IOMUXC_FEC_FEC_RDATA_2_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x50cU)
#define IOMUXC_FEC_FEC_RDATA_3_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x510U)
#define IOMUXC_FEC_FEC_RX_CLK_SELECT_INPUT     				(IOMUXC_BASE_ADDR+0x514U)
#define IOMUXC_FEC_FEC_RX_ER_SELECT_INPUT     				(IOMUXC_BASE_ADDR+0x518U)

#define IOMUXC_I2C2_IPP_SCL_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x51cU)
#define IOMUXC_I2C2_IPP_SDA_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x520U)
#define IOMUXC_I2C3_IPP_SCL_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x524U)
#define IOMUXC_I2C3_IPP_SDA_IN_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x528U)

#define IOMUXC_KPP_IPP_IND_COL_4_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x52cU)
#define IOMUXC_KPP_IPP_IND_COL_5_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x530U)
#define IOMUXC_KPP_IPP_IND_COL_6_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x534U)
#define IOMUXC_KPP_IPP_IND_COL_7_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x538U)
#define IOMUXC_KPP_IPP_IND_ROW_4_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x53cU)
#define IOMUXC_KPP_IPP_IND_ROW_5_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x540U)
#define IOMUXC_KPP_IPP_IND_ROW_6_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x544U)
#define IOMUXC_KPP_IPP_IND_ROW_7_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x548U)

#define IOMUXC_SIM1_PIN_SIM_RCVD1_IN_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x54cU)
#define IOMUXC_SIM1_PIN_SIM_SIMPD1_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x550U)
#define IOMUXC_SIM1_SIM_RCVD1_IO_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x554U)
#define IOMUXC_SIM2_PIN_SIM_RCVD1_IN_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x558U)
#define IOMUXC_SIM2_PIN_SIM_SIMPD1_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x55cU)
#define IOMUXC_SIM2_SIM_RCVD1_IO_SELECT_INPUT     			(IOMUXC_BASE_ADDR+0x560U)

#define IOMUXC_UART3_IPP_UART_RTS_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x564U)
#define IOMUXC_UART3_IPP_UART_RXD_MUX_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x568U)
#define IOMUXC_UART4_IPP_UART_RTS_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x56cU)
#define IOMUXC_UART4_IPP_UART_RXD_MUX_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x570U)
#define IOMUXC_UART5_IPP_UART_RTS_B_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x574U)
#define IOMUXC_UART5_IPP_UART_RXD_MUX_SELECT_INPUT     		(IOMUXC_BASE_ADDR+0x578U)

#define IOMUXC_USB_TOP_IPP_IND_OTG_USB_OC_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x57cU)
#define IOMUXC_USB_TOP_IPP_IND_UH2_USB_OC_SELECT_INPUT     	(IOMUXC_BASE_ADDR+0x580U)


//------------------------------------------------------------------------------
// REGISTER BIT FIELD POSITIONS (LEFT SHIFT)
//------------------------------------------------------------------------------
//SW_MUX_CTL Register
#define IOMUXC_SW_MUX_CTL_MUX_MODE_LSH     		0
#define IOMUXC_SW_MUX_CTL_SION_LSH     			4

//SW_SELECT_INPUT Register
#define IOMUXC_SELECT_INPUT_SELECT_INPUT_LSH    0

//Software Pad Control (SW_PAD_CTL)
#define IOMUXC_SW_PAD_CTL_SRE_LSH     			0
#define IOMUXC_SW_PAD_CTL_DSE_LSH     			1
#define IOMUXC_SW_PAD_CTL_ODE_LSH     			3
#define IOMUXC_SW_PAD_CTL_PUS_LSH     			4
#define IOMUXC_SW_PAD_CTL_PUE_LSH     			6
#define IOMUXC_SW_PAD_CTL_PKE_LSH     			7 		//DDR Pads have only this Bit
#define IOMUXC_SW_PAD_CTL_HYS_LSH     			8
#define IOMUXC_SW_PAD_CTL_DVS_LSH     			13

//SW_PAD_CTL_GRP Register
#define IOMUXC_SW_PAD_CTL_GRP_DDRTYPE_LSH		11		//Default Setting is Mobile DDR

//Drive Voltage Select (DVS) group control register
#define IOMUXC_SW_PAD_CTL_GRP_DVS_LSH     		13

//Drive Strength group control register
#define IOMUXC_SW_PAD_CTL_GRP_DSE_LSH     		1

//General Purpose Register (GPR)
#define IOMUXC_GPR1_SDCTL_CS2_SEL_B_LSH  		0  	//Changed Name from RM
#define IOMUXC_GPR1_SDCTL_CS3_SEL_B_LSH  		1  	//Changed Name from RM

//Interrupt Observe Control Register (INT_OBSRV)
#define IOMUXC_IINT_OBSRV_OBSRV_LSH				0


//------------------------------------------------------------------------------
// REGISTER BIT FIELD WIDTHS
//------------------------------------------------------------------------------
//SW_MUX_CTL Register
#define IOMUXC_SW_MUX_CTL_MUX_MODE_WID    		Width_3
#define IOMUXC_SW_MUX_CTL_SION_WID    			Width_1

//SW_SELECT_INPUT Register
#define IOMUXC_SELECT_INPUT_SELECT_INPUT_WID	Width_3

//Software Pad Control (SW_PAD_CTL)
#define IOMUXC_SW_PAD_CTL_SRE_WID    			Width_1
#define IOMUXC_SW_PAD_CTL_DSE_WID    			Width_2
#define IOMUXC_SW_PAD_CTL_ODE_WID    			Width_1
#define IOMUXC_SW_PAD_CTL_PUS_WID    			Width_2
#define IOMUXC_SW_PAD_CTL_PUE_WID    			Width_1
#define IOMUXC_SW_PAD_CTL_PKE_WID    			Width_1 		//DDR Pads have only this Bit
#define IOMUXC_SW_PAD_CTL_HYS_WID    			Width_1
#define IOMUXC_SW_PAD_CTL_DVS_WID    			Width_1

//SW_PAD_CTL_GRP Register
#define IOMUXC_SW_PAD_CTL_GRP_DDRTYPE_WID		Width_2

//Drive Voltage Select (DVS) group control register
#define IOMUXC_SW_PAD_CTL_GRP_DVS_WID			Width_1

//Drive Strength group control register
#define IOMUXC_SW_PAD_CTL_GRP_DSE_WID			Width_2

//General Purpose Register (GPR)
#define IOMUXC_GPR1_SDCTL_CS2_SEL_B_WID			Width_1
#define IOMUXC_GPR1_SDCTL_CS3_SEL_B_WID			Width_1

//Interrupt Observe Control Register (INT_OBSRV)
#define IOMUXC_IINT_OBSRV_OBSRV_WID				Width_7

//------------------------------------------------------------------------------
// REGISTER BIT WRITE VALUES
//------------------------------------------------------------------------------
#define MUX_MODE_0		0x0		//000: Select ALT0 mux mode. (default)
#define MUX_MODE_1		0x1		//001: Select ALT1 mux mode.
#define MUX_MODE_2		0x2		//010: Select ALT2 mux mode.
#define MUX_MODE_3		0x3		//011: Select ALT3 mux mode.
#define MUX_MODE_4		0x4		//100: Select ALT4 mux mode.
#define MUX_MODE_5		0x5		//101: Select ALT5 mux mode(usually GPIO).
#define MUX_MODE_6		0x6		//110: Select ALT6 mux mode.
#define MUX_MODE_7		0x7		//111: Select ALT7 mux mode (Trace).
#define MUX_MODE_TRACE	0x7		//111: Select ALT7 mux mode (Trace).

#define PAD_CTL_DVS_33				0		//Drive Voltage Select 3.3-V IO Drive
#define PAD_CTL_DVS_18				1		//Drive Voltage Select 1.8-V IO Drive

#define PAD_CTL_HYS_DISABLE			0		//Hysteresis Disabled, CMOS input.
#define PAD_CTL_HYS_ENABLE			1		//Hysteresis Enabled, Schmitt trigger input.

#define PAD_CTL_PKE_DISABLE			0		//Pull/Keeper Disabled
#define PAD_CTL_PKE_ENABLE			1		//Pull/Keeper Enabled

#define PAD_CTL_PUE_KEEPER			0		//Keeper Enabled
#define PAD_CTL_PUE_PULL			1		//Pull Up or Down Enabled

#define PAD_CTL_PUS_100KPULLDOWN	0		//100KOhm Pull Down
#define PAD_CTL_PUS_47KPULLUP		1		//47KOhm Pull Up
#define PAD_CTL_PUS_100KPULLUP		2		//100KOhm Pull Up
#define PAD_CTL_PUS_22KPULLUP		3		//22KOhm Pull Up

#define PAD_CTL_ODE_OUTCMOS			0		//Output is CMOS
#define PAD_CTL_ODE_OUTOPENDRAIN	1		//Output is Open Drain

#define PAD_CTL_DSE_NORMAL			0		//Normal Drive Strength
#define PAD_CTL_DSE_HIGH			1		//High Drive Strength
#define PAD_CTL_DSE_MAX				2		//MAX Drive Strength

#define PAD_CTL_SRE_SLOW			0		//Slow slew rate, compatible to Neptune pads
#define PAD_CTL_SRE_FAST			1		//Fast slew rate, used for high frequency designs

#endif /*IMX25_IOMUX_H_*/


